defaults: &defaults
  # for mongoid 3+
  sessions:
    default:
      hosts:
        - localhost:27017

development:
  <<: *defaults
  sessions:
    default:
      database: dummy_development
      hosts:
        - localhost:27017

test:
  <<: *defaults
  sessions:
    default:
      database: dummy_test
      hosts:
        - localhost:27017

# set these environment variables on your prod server
production:
  sessions:
    default:
      hosts: 
        - "#{ENV['MONGOID_HOST']}:#{ENV['MONGOID_PORT']}"
      username: <%= ENV['MONGOID_USERNAME'] %>
      password: <%= ENV['MONGOID_PASSWORD'] %>
      database: <%= ENV['MONGOID_DATABASE'] %>
